title: Dean Payne
description: Software Developer
site_title: '@deanpayne6 - Dean Payne'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: deanpayne6
blog_url: 'https://deanpayne6.github.io/'
email: deandeanpayne@gmail.com

# absolute or relative
profile_picture: assets\images\LINKED.jpg

# Google Analytics ID
google_analytics: 